#!/usr/bin/env node
var app = require('../app'),
    socket = require('socket.io'),
    http = require("http");

app.set('port', process.env.PORT || 3000);

/*var server = app.listen(app.get('port'), function() {
  console.log('Express server listening on port ' + server.address().port);
});*/


var server = http.createServer(app);
var io = socket.listen(server);

server.listen(app.get('port'), function(){

    require("../service/chat").initChatServer(io);
    console.log("Express server listening on port %d in %s mode", app.get('port'), app.get('env'));
});